steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - 'build'
      - '-t'
      - '$_AR_HOSTNAME/$PROJECT_ID/hello-world-repo/go-micro:$COMMIT_SHA'
      - "-t"
      - $_AR_HOSTNAME/$PROJECT_ID/hello-world-repo/go-micro:latest'
      - "."
  - name: "gcr.io/cloud-builders/docker"
    args:
      - 'push'
      - '$_AR_HOSTNAME/$PROJECT_ID/hello-world-repo/go-micro'
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'go-micro-service'
      - '--image'
      - '$_AR_HOSTNAME/$PROJECT_ID/hello-world-repo/go-micro:$COMMIT_SHA'
      - '--region'
      - '$_REGION'
substitutions:
  _AR_HOST_NAME: us-centra1-docker.pkg.dev
  _REGION: us-central1

